'use strict';

const mongoose = require('mongoose');

// ─── Report Schema ────────────────────────────────────────────────────────────
const reportSchema = new mongoose.Schema(
  {
    // Report type
    type: {
      type: String,
      enum: [
        'patient_demographics',
        'doctor_performance',
        'appointment_analytics',
        'billing_revenue',
        'prescription_trends',
        'financial_summary',
        'occupancy_rate',
        'revenue_forecast',
        'custom',
      ],
      required: [true, 'Report type is required'],
    },

    // Title & Description
    title: {
      type: String,
      required: [true, 'Report title is required'],
      trim: true,
      maxlength: [200, 'Title cannot exceed 200 characters'],
    },

    description: {
      type: String,
      trim: true,
      default: '',
      maxlength: [500, 'Description cannot exceed 500 characters'],
    },

    // Date range
    startDate: {
      type: Date,
      required: [true, 'Start date is required'],
    },

    endDate: {
      type: Date,
      required: [true, 'End date is required'],
    },

    // Report data
    data: {
      type: mongoose.Schema.Types.Mixed,
      default: {},
    },

    // Summary statistics
    summary: {
      totalRecords: { type: Number, default: 0 },
      totalAmount: { type: Number, default: 0 },
      averageValue: { type: Number, default: 0 },
      growth: { type: Number, default: 0 }, // Percentage growth
    },

    // Filters applied
    filters: {
      type: mongoose.Schema.Types.Mixed,
      default: {},
    },

    // Report format
    format: {
      type: String,
      enum: ['json', 'csv', 'pdf'],
      default: 'json',
    },

    // Generated by
    generatedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },

    // Scheduling
    isScheduled: {
      type: Boolean,
      default: false,
    },

    scheduleFrequency: {
      type: String,
      enum: ['daily', 'weekly', 'monthly', 'quarterly', 'yearly', 'none'],
      default: 'none',
    },

    nextScheduledDate: {
      type: Date,
      default: null,
    },

    // Distribution list
    emailRecipients: {
      type: [String],
      default: [],
    },

    // Report status
    status: {
      type: String,
      enum: ['draft', 'generated', 'sent', 'archived'],
      default: 'draft',
    },

    // Access control
    visibility: {
      type: String,
      enum: ['private', 'team', 'public'],
      default: 'private',
    },

    // Audit
    isDeleted: {
      type: Boolean,
      default: false,
      select: false,
    },

    deletedAt: {
      type: Date,
      default: null,
      select: false,
    },
  },
  {
    timestamps: true,
    toJSON: { virtuals: true },
    toObject: { virtuals: true },
  },
);

// ─── Indexes ──────────────────────────────────────────────────────────────────
reportSchema.index({ type: 1 });
reportSchema.index({ generatedBy: 1 });
reportSchema.index({ createdAt: -1 });
reportSchema.index({ status: 1 });
reportSchema.index({ isScheduled: 1, nextScheduledDate: 1 });
reportSchema.index({ isDeleted: 1 });

// ─── Query helpers — always exclude soft-deleted records by default ───────────
reportSchema.pre(/^find/, function (next) {
  if (this.getFilter().isDeleted === undefined) {
    this.where({ isDeleted: false });
  }
  next();
});

const Report = mongoose.model('Report', reportSchema);
module.exports = Report;
